[stage-app-servers]
web1 ansible_host=x.x.x.x
web2 ansible_host=x.x.x.x
web3 ansible_host=x.x.x.x
web4 ansible_host=x.x.x.x

[stage-app-servers:vars]
ansible_user=x
ansible_ssh_private_key_file=~/.ssh/id_ed25519
